"""Tests for template rendering functions."""

from __future__ import annotations

from pathlib import Path

import pytest

from ai_scaffold.providers import AI_PROVIDERS
from ai_scaffold.scaffold import ScaffoldConfig
from ai_scaffold.templates import (
    _render_docker,
    _render_env_example,
    render_all,
)


def make_config(tmp_path: Path, **kwargs) -> ScaffoldConfig:
    defaults = dict(
        project_name="test-app",
        ai_provider="openai",
        auth_provider="clerk",
        db_provider="sqlite",
        payment_provider="stripe",
        monitoring=False,
        docker=True,
        ci=False,
        output_dir=tmp_path,
    )
    defaults.update(kwargs)
    return ScaffoldConfig(**defaults)


# ---------------------------------------------------------------------------
# _render_env_example
# ---------------------------------------------------------------------------

class TestRenderEnvExample:
    def test_contains_header_comment(self, tmp_path):
        config = make_config(tmp_path)
        paths = _render_env_example(config, tmp_path)
        content = paths[0].read_text()
        assert "Auto-generated by ai-scaffold" in content

    def test_contains_app_env_var(self, tmp_path):
        config = make_config(tmp_path)
        paths = _render_env_example(config, tmp_path)
        content = paths[0].read_text()
        assert "APP_ENV=development" in content
        assert "SECRET_KEY=change-me-in-production" in content

    def test_contains_ai_provider_key(self, tmp_path):
        config = make_config(tmp_path, ai_provider="openai")
        paths = _render_env_example(config, tmp_path)
        content = paths[0].read_text()
        assert "OPENAI_API_KEY=" in content

    def test_contains_anthropic_key(self, tmp_path):
        config = make_config(tmp_path, ai_provider="anthropic")
        paths = _render_env_example(config, tmp_path)
        content = paths[0].read_text()
        assert "ANTHROPIC_API_KEY=" in content

    def test_contains_gemini_key(self, tmp_path):
        config = make_config(tmp_path, ai_provider="gemini")
        paths = _render_env_example(config, tmp_path)
        content = paths[0].read_text()
        assert "GOOGLE_API_KEY=" in content

    def test_stripe_vars_present_when_payment_is_stripe(self, tmp_path):
        config = make_config(tmp_path, payment_provider="stripe")
        paths = _render_env_example(config, tmp_path)
        content = paths[0].read_text()
        assert "STRIPE_SECRET_KEY=" in content

    def test_payment_section_absent_when_none(self, tmp_path):
        config = make_config(tmp_path, payment_provider="none")
        paths = _render_env_example(config, tmp_path)
        content = paths[0].read_text()
        assert "STRIPE_SECRET_KEY" not in content
        assert "LEMONSQUEEZY" not in content

    def test_sentry_dsn_present_when_monitoring_enabled(self, tmp_path):
        config = make_config(tmp_path, monitoring=True)
        paths = _render_env_example(config, tmp_path)
        content = paths[0].read_text()
        assert "SENTRY_DSN=" in content

    def test_sentry_dsn_absent_when_monitoring_disabled(self, tmp_path):
        config = make_config(tmp_path, monitoring=False)
        paths = _render_env_example(config, tmp_path)
        content = paths[0].read_text()
        assert "SENTRY_DSN" not in content

    def test_returns_single_path(self, tmp_path):
        config = make_config(tmp_path)
        paths = _render_env_example(config, tmp_path)
        assert len(paths) == 1
        assert paths[0].name == ".env.example"

    def test_file_is_written_to_disk(self, tmp_path):
        config = make_config(tmp_path)
        paths = _render_env_example(config, tmp_path)
        assert paths[0].exists()

    def test_model_default_included(self, tmp_path):
        config = make_config(tmp_path, ai_provider="openai")
        paths = _render_env_example(config, tmp_path)
        content = paths[0].read_text()
        assert "AI_MODEL=gpt-4o" in content


# ---------------------------------------------------------------------------
# _render_docker
# ---------------------------------------------------------------------------

class TestRenderDocker:
    def test_creates_dockerfile(self, tmp_path):
        config = make_config(tmp_path)
        paths = _render_docker(config, tmp_path)
        names = [p.name for p in paths]
        assert "Dockerfile" in names

    def test_creates_compose_file(self, tmp_path):
        config = make_config(tmp_path)
        paths = _render_docker(config, tmp_path)
        names = [p.name for p in paths]
        assert "docker-compose.yml" in names

    def test_dockerfile_uses_python_slim(self, tmp_path):
        config = make_config(tmp_path)
        paths = _render_docker(config, tmp_path)
        dockerfile = next(p for p in paths if p.name == "Dockerfile")
        content = dockerfile.read_text()
        assert "python:3.12-slim" in content

    def test_dockerfile_exposes_port_8000(self, tmp_path):
        config = make_config(tmp_path)
        paths = _render_docker(config, tmp_path)
        dockerfile = next(p for p in paths if p.name == "Dockerfile")
        content = dockerfile.read_text()
        assert "EXPOSE 8000" in content

    def test_compose_references_project_name(self, tmp_path):
        config = make_config(tmp_path, project_name="my-unique-app")
        paths = _render_docker(config, tmp_path)
        compose = next(p for p in paths if p.name == "docker-compose.yml")
        content = compose.read_text()
        assert "my-unique-app" in content

    def test_dockerfile_has_uvicorn_cmd(self, tmp_path):
        config = make_config(tmp_path)
        paths = _render_docker(config, tmp_path)
        dockerfile = next(p for p in paths if p.name == "Dockerfile")
        content = dockerfile.read_text()
        assert "uvicorn" in content


# ---------------------------------------------------------------------------
# All AI provider templates render without error
# ---------------------------------------------------------------------------

class TestAllAIProvidersRender:
    @pytest.mark.parametrize("ai_provider", list(AI_PROVIDERS.keys()))
    def test_render_all_succeeds(self, tmp_path, ai_provider):
        config = make_config(
            tmp_path,
            ai_provider=ai_provider,
            docker=True,
            ci=True,
            monitoring=True,
        )
        project_dir = tmp_path / config.project_name
        project_dir.mkdir(parents=True, exist_ok=True)
        files = render_all(config, project_dir)
        assert len(files) > 0

    @pytest.mark.parametrize("ai_provider", list(AI_PROVIDERS.keys()))
    def test_env_example_has_ai_section(self, tmp_path, ai_provider):
        config = make_config(tmp_path, ai_provider=ai_provider)
        paths = _render_env_example(config, tmp_path)
        content = paths[0].read_text()
        # Each AI provider must mention the provider name in a comment
        assert f"# AI — {ai_provider}" in content
