"""Template rendering — generates all project files from config."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ai_scaffold.scaffold import ScaffoldConfig


def render_all(config: ScaffoldConfig, project_dir: Path) -> list[Path]:
    """Render all project files and return list of created paths."""
    files: list[Path] = []

    renderers = [
        _render_env_example,
        _render_gitignore,
        _render_readme,
        _render_backend,
        _render_pyproject,
    ]

    if config.docker:
        renderers.append(_render_docker)

    if config.ci:
        renderers.append(_render_ci)

    if config.monitoring:
        renderers.append(_render_monitoring)

    for renderer in renderers:
        created = renderer(config, project_dir)
        files.extend(created)

    return files


# ---------------------------------------------------------------------------
# Individual file renderers
# ---------------------------------------------------------------------------

def _write(path: Path, content: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path


def _render_env_example(config: ScaffoldConfig, root: Path) -> list[Path]:
    lines = ["# Auto-generated by ai-scaffold", "# Copy to .env and fill in your values", ""]
    lines.append("# App")
    lines.append("APP_ENV=development")
    lines.append("SECRET_KEY=change-me-in-production")
    lines.append("ALLOWED_ORIGINS=http://localhost:3000")
    lines.append("")

    # AI
    lines.append(f"# AI — {config.ai_provider}")
    for var in config.ai_info.get("env_vars", []):
        lines.append(f"{var}=")
    lines.append(f"AI_MODEL={config.ai_info.get('model_default', '')}")
    lines.append("")

    # Auth
    lines.append(f"# Auth — {config.auth_provider}")
    for var in config.auth_info.get("env_vars", []):
        lines.append(f"{var}=")
    lines.append("")

    # DB
    lines.append(f"# Database — {config.db_provider}")
    for var in config.db_info.get("env_vars", []):
        lines.append(f"{var}=")
    lines.append("")

    # Payments
    if config.payment_provider != "none":
        lines.append(f"# Payments — {config.payment_provider}")
        for var in config.payment_info.get("env_vars", []):
            lines.append(f"{var}=")
        lines.append("")

    # Monitoring
    if config.monitoring:
        lines.append("# Monitoring")
        lines.append("SENTRY_DSN=")
        lines.append("")

    return [_write(root / ".env.example", "\n".join(lines))]


def _render_gitignore(config: ScaffoldConfig, root: Path) -> list[Path]:
    content = """\
# Environment
.env
.env.local
.env.*.local

# Python
__pycache__/
*.py[cod]
*.egg-info/
dist/
build/
.venv/
venv/
.pytest_cache/
.mypy_cache/
.ruff_cache/
htmlcov/
.coverage

# Node
node_modules/
.next/
out/
.vercel/

# IDE
.vscode/
.idea/
*.swp

# OS
.DS_Store
Thumbs.db

# Secrets
*.pem
*.key
"""
    return [_write(root / ".gitignore", content)]


def _render_readme(config: ScaffoldConfig, root: Path) -> list[Path]:
    name = config.project_name
    ai = config.ai_provider
    auth = config.auth_provider
    db = config.db_provider
    pay = config.payment_provider

    env_vars_block = "\n".join(f"  {v}=" for v in config.all_env_vars)

    content = f"""\
# {name}

> Production-ready AI application — scaffolded by [ai-scaffold](https://github.com/serenakeyitan/ai-app-scaffold)

## Stack

| Layer | Technology |
|-------|-----------|
| AI | {ai} |
| Auth | {auth} |
| Database | {db} |
| Payments | {pay} |
| Monitoring | {"Sentry" if config.monitoring else "—"} |
| Infra | {"Docker + GitHub Actions" if config.docker and config.ci else "—"} |

## Quick Start

```bash
# 1. Clone and enter project
cd {name}

# 2. Set up environment
cp .env.example .env
# Edit .env with your API keys

# 3. Install Python dependencies
python -m venv .venv && source .venv/bin/activate
pip install -e .

# 4. Start the server
{"docker compose up" if config.docker else "uvicorn app.main:app --reload"}
```

## Environment Variables

```env
{env_vars_block}
```

## API Reference

| Method | Path | Description |
|--------|------|-------------|
| GET | `/health` | Health check |
| POST | `/api/chat` | Chat completion |
| GET | `/api/user/me` | Current user (auth required) |
| POST | `/api/webhooks/payments` | Payment webhook |

## Project Structure

```
{name}/
├── app/
│   ├── main.py          # FastAPI application factory
│   ├── settings.py      # Pydantic settings from env vars
│   ├── routes/
│   │   ├── chat.py      # AI chat endpoint
│   │   ├── auth.py      # Auth middleware/routes
│   │   └── webhooks.py  # Payment webhooks
│   ├── db/
│   │   └── models.py    # SQLAlchemy models
│   └── services/
│       ├── ai.py        # AI provider client
│       └── payments.py  # Payment provider client
├── .env.example
├── .gitignore
{"├── Dockerfile" if config.docker else ""}
{"├── docker-compose.yml" if config.docker else ""}
└── pyproject.toml
```

## Deployment

The project is ready to deploy to:

- **[Fly.io](https://fly.io)**: `flyctl launch && flyctl deploy`
- **[Railway](https://railway.app)**: Connect GitHub repo, add env vars
- **[Render](https://render.com)**: Use the included `Dockerfile`

---

*Scaffolded with [ai-scaffold](https://github.com/serenakeyitan/ai-app-scaffold) — zero-to-prod in one command.*
"""
    return [_write(root / "README.md", content)]


def _render_backend(config: ScaffoldConfig, root: Path) -> list[Path]:
    files: list[Path] = []

    # app/__init__.py
    files.append(_write(root / "app" / "__init__.py", '"""AI app — scaffolded by ai-scaffold."""\n'))

    # app/settings.py
    settings_content = f"""\
\"\"\"Application settings loaded from environment variables.\"\"\"

from __future__ import annotations

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")

    APP_ENV: str = "development"
    SECRET_KEY: str = "change-me"
    ALLOWED_ORIGINS: list[str] = ["http://localhost:3000"]

    # AI — {config.ai_provider}
"""
    for var in config.ai_info.get("env_vars", []):
        settings_content += f"    {var}: str = \"\"\n"
    settings_content += f'    AI_MODEL: str = "{config.ai_info.get("model_default", "")}"\n'
    settings_content += "\n"

    if config.db_provider not in ("sqlite",):
        settings_content += f"    # Database — {config.db_provider}\n"
        for var in config.db_info.get("env_vars", []):
            settings_content += f'    {var}: str = ""\n'
        settings_content += "\n"

    if config.monitoring:
        settings_content += "    # Monitoring\n"
        settings_content += '    SENTRY_DSN: str = ""\n\n'

    settings_content += "\nsettings = Settings()\n"
    files.append(_write(root / "app" / "settings.py", settings_content))

    # app/main.py
    sentry_import = ""
    sentry_init = ""
    if config.monitoring:
        sentry_import = "import sentry_sdk\n"
        sentry_init = """\

if settings.SENTRY_DSN:
    sentry_sdk.init(dsn=settings.SENTRY_DSN, traces_sample_rate=0.2)
"""

    main_content = f"""\
\"\"\"FastAPI application factory.\"\"\"

from __future__ import annotations

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
{sentry_import}
from app.settings import settings
from app.routes import chat, webhooks
{sentry_init}

def create_app() -> FastAPI:
    app = FastAPI(
        title="{config.project_name}",
        description="AI-powered application",
        version="0.1.0",
    )

    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.ALLOWED_ORIGINS,
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    app.include_router(chat.router, prefix="/api")
    app.include_router(webhooks.router, prefix="/api/webhooks")

    @app.get("/health")
    async def health() -> dict:
        return {{"status": "ok", "env": settings.APP_ENV}}

    return app


app = create_app()
"""
    files.append(_write(root / "app" / "main.py", main_content))

    # app/routes/__init__.py
    files.append(_write(root / "app" / "routes" / "__init__.py", ""))

    # app/routes/chat.py  — AI provider wired in
    ai = config.ai_info
    chat_content = f"""\
\"\"\"Chat completion route — powered by {config.ai_provider}.\"\"\"

from __future__ import annotations

import os
from typing import Any

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from app.settings import settings

{ai["import"]}

router = APIRouter()


class ChatRequest(BaseModel):
    messages: list[dict[str, Any]]


class ChatResponse(BaseModel):
    reply: str


@router.post("/chat", response_model=ChatResponse)
async def chat(req: ChatRequest) -> ChatResponse:
    \"\"\"Send messages to the AI provider and return the reply.\"\"\"
    try:
        {ai["client_init"]}
        # {ai["chat_call"].splitlines()[0]}
        reply = _extract_reply(client, req.messages, settings)
        return ChatResponse(reply=reply)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc


def _extract_reply(client: Any, messages: list[dict], settings: Any) -> str:  # noqa: ANN401
    \"\"\"Provider-specific reply extraction — swap in your own logic.\"\"\"
    raise NotImplementedError(
        "Wire up your AI provider call here. See the docs for examples."
    )
"""
    files.append(_write(root / "app" / "routes" / "chat.py", chat_content))

    # app/routes/webhooks.py
    webhook_content = f"""\
\"\"\"Payment webhook handler — {config.payment_provider}.\"\"\"

from __future__ import annotations

import hashlib
import hmac
import os

from fastapi import APIRouter, Header, HTTPException, Request

from app.settings import settings

router = APIRouter()


@router.post("/payments")
async def payments_webhook(
    request: Request,
    stripe_signature: str | None = Header(default=None),
) -> dict:
    \"\"\"Receive and verify payment events from {config.payment_provider}.\"\"\"
    payload = await request.body()

    # TODO: verify webhook signature using your provider's SDK
    # Example (Stripe):
    #   import stripe
    #   event = stripe.Webhook.construct_event(
    #       payload, stripe_signature, settings.STRIPE_WEBHOOK_SECRET
    #   )

    return {{"received": True}}
"""
    files.append(_write(root / "app" / "routes" / "webhooks.py", webhook_content))

    # app/db/models.py
    files.append(_write(root / "app" / "db" / "__init__.py", ""))
    db_content = """\
\"\"\"SQLAlchemy models.\"\"\"

from __future__ import annotations

from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Integer, String, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    external_id: Mapped[str] = mapped_column(String(255), unique=True, index=True)
    email: Mapped[str] = mapped_column(String(255), unique=True, index=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    conversations: Mapped[list["Conversation"]] = relationship(back_populates="user")


class Conversation(Base):
    __tablename__ = "conversations"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"))
    title: Mapped[str] = mapped_column(String(255), default="New conversation")
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    user: Mapped["User"] = relationship(back_populates="conversations")
    messages: Mapped[list["Message"]] = relationship(back_populates="conversation")


class Message(Base):
    __tablename__ = "messages"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    conversation_id: Mapped[int] = mapped_column(ForeignKey("conversations.id"))
    role: Mapped[str] = mapped_column(String(32))  # "user" | "assistant"
    content: Mapped[str] = mapped_column(String)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    conversation: Mapped["Conversation"] = relationship(back_populates="messages")
"""
    files.append(_write(root / "app" / "db" / "models.py", db_content))

    # pyproject for the scaffolded app
    app_pyproject = f"""\
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "{config.project_name}"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.111.0",
    "uvicorn[standard]>=0.29.0",
    "pydantic-settings>=2.2.0",
    "sqlalchemy>=2.0.0",
    "{config.ai_info['sdk']}",
{"    'sentry-sdk[fastapi]'," if config.monitoring else ""}
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
    "pytest-asyncio>=0.23.0",
    "httpx>=0.27.0",
]
"""
    files.append(_write(root / "pyproject.toml", app_pyproject))

    return files


def _render_pyproject(config: ScaffoldConfig, root: Path) -> list[Path]:
    # Already written by _render_backend; no-op here
    return []


def _render_docker(config: ScaffoldConfig, root: Path) -> list[Path]:
    files: list[Path] = []

    dockerfile = """\
FROM python:3.12-slim

WORKDIR /app

# Install dependencies
COPY pyproject.toml .
RUN pip install --no-cache-dir -e .

# Copy source
COPY app/ ./app/

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
"""
    files.append(_write(root / "Dockerfile", dockerfile))

    compose = f"""\
version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: ${{POSTGRES_PASSWORD:-secret}}
      POSTGRES_DB: {config.project_name}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
"""
    files.append(_write(root / "docker-compose.yml", compose))
    return files


def _render_ci(config: ScaffoldConfig, root: Path) -> list[Path]:
    ci_content = """\
name: CI

on:
  push:
    branches: [main, initial-build]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -e ".[dev]"

      - name: Lint
        run: |
          pip install ruff
          ruff check .

      - name: Test
        run: pytest tests/ -v
"""
    return [_write(root / ".github" / "workflows" / "ci.yml", ci_content)]


def _render_monitoring(config: ScaffoldConfig, root: Path) -> list[Path]:
    content = """\
\"\"\"Monitoring helpers — Sentry + basic /metrics endpoint.\"\"\"

from __future__ import annotations

from fastapi import APIRouter

router = APIRouter()


@router.get("/metrics")
async def metrics() -> dict:
    \"\"\"Basic health metrics endpoint.\"\"\"
    import os
    import sys

    return {
        "python_version": sys.version,
        "pid": os.getpid(),
        "status": "ok",
    }
"""
    return [_write(root / "app" / "monitoring.py", content)]
